apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: collection-instrument
  namespace: {{ .Values.namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-manager
  refreshInterval: 1m
  data:
  - secretKey: crypto-key
    remoteRef:
      key: collection-instrument
      version: latest