{{- if .Values.sdx.rabbitMQ.enabled }}
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: sdx-rabbitmq
  namespace: {{ .Values.namespace }}
spec:
  backendType: gcpSecretsManager
  projectId: {{ .Values.gcp.project }}
  data:
    - key: sdx-rabbitmq
      name: rabbitmq-username
      version: latest
      property: rabbitmq-username
    - key: sdx-rabbitmq
      name: rabbitmq-password
      version: latest
      property: rabbitmq-password
{{- end }}

---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: collection-instrument
  namespace: {{ .Values.namespace }}
spec:
  backendType: gcpSecretsManager
  projectId: {{ .Values.gcp.project }}
  data:
    - key: collection-instrument
      name: crypto-key
      version: latest
