apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: collection-instrument
  namespace: {{ .Values.namespace }}
spec:
  backendType: gcpSecretsManager
  projectId: {{ .Values.gcp.project }}
  data:
    - key: collection-instrument
      name: crypto-key
      version: latest


---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: seft-collection-instrument-key
  namespace: {{ .Values.namespace }}
spec:
  backendType: gcpSecretsManager
  projectId: {{ .Values.gcp.project }}
  data:
    - key: seft-collection-instrument-key
      name: gpg-public-crypto-key
      version: 7
