apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: collection-instrument
  namespace: {{ .Values.namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-secret-store
  target:
    name: collection-instrument
  data:
  - secretKey: crypto-key
    remoteRef:
      key: collection-instrument
      version: latest