namespace: minikube
env: minikube

image:
  devRepo: eu.gcr.io/ons-rasrmbs-management
  name: eu.gcr.io/ons-rasrmbs-management
  tag: latest
  pullPolicy: Always

database:
  managedPostgres: false
  sqlProxyEnabled: false
  secrets:
    usernameKey: username
    passwordKey: password
    nameKey: db-name

container:
  port: 8080
service:
  port: 8080

resources:
  requests:
    memory: "500Mi"
    cpu: "10m"
  limits:
    memory: "1000Mi"
    cpu: "50m"

autoscaling: false
scaleAt:
  # These are expressed as a percentage of resources.requests, not resources.limits
  memoryPercentage: 150
  cpuPercentage: 250
replicas: 1
rollingUpdate:
  maxSurge: 1
  maxUnavailable: 1

cryptoKey: "supersecure"

managedRabbitMQ:
  enabled: false

sdx:
  rabbitMQ:
    enabled: false
    external: true
    host: "127.0.0.1"
    port: "5672"
    username: guest
    password: guest

dns:
  enabled: false
  wellKnownPort: 8080