namespace: minikube
env: minikube

image:
  devRepo: europe-west2-docker.pkg.dev/ons-ci-rmrasbs/images
  name: europe-west2-docker.pkg.dev/ons-ci-rmrasbs/images
  tag: latest
  pullPolicy: Always

database:
  managedPostgres: false
  sqlProxyEnabled: false
  secrets:
    usernameKey: username
    passwordKey: password
    nameKey: db-name

container:
  port: 8080
service:
  port: 8080

resources:
  application:
    requests:
      memory: "600Mi"
      cpu: "350m"
    limits:
      memory: "700Mi"
      cpu: "400m"
  proxy:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "100m"

autoscaling: false
scaleAt:
  # These are expressed as a percentage of resources.requests, not resources.limits
  memoryPercentage: 150
  cpuPercentage: 200
replicas: 1
maxReplicas: 1
rollingUpdate:
  maxSurge: 1
  maxUnavailable: 1

dns:
  enabled: false
  wellKnownPort: 8080

gcp:
  project: ras-rm-sandbox
  collectionInstrument:
    bucket:
      name: "ras-rm-seft-ci-dev"
      prefix: ""

loadBalancer:
  ipAddress: 10.110.128.13
  enabled: false