env: minikube

replicas: 1
rollingUpdate:
  maxSurge: 1
  maxUnavailable: 1

image:
  name: eu.gcr.io/ons-rasrmbs-management
  tag: latest
  pullPolicy: Always

database:
  managedPostgres: false
  sqlProxyEnabled: false
  secrets:
    usernameKey: username
    passwordKey: password
    nameKey: db-name

container:
  port: 8080
service:
  port: 8080

resources:
  requests:
    memory: "256Mi"

cryptoKey: "supersecure"

managedRabbitMQ:
  enabled: false

sdx:
  rabbitMQ:
    enabled: false
    host: "127.0.0.1"
    port: "5672"
    username: guest
    password: guest

dns:
  enabled: false
  wellKnownPort: 8080