namespace: minikube
env: minikube

image:
  devRepo: eu.gcr.io/ons-rasrmbs-management
  name: eu.gcr.io/ons-rasrmbs-management
  tag: latest
  pullPolicy: Always

database:
  managedPostgres: false
  sqlProxyEnabled: false
  secrets:
    usernameKey: username
    passwordKey: password
    nameKey: db-name

container:
  port: 8080
service:
  port: 8080

resources:
  application:
    requests:
      memory: "600Mi"
      cpu: "230m"
    limits:
      memory: "700Mi"
      cpu: "320m"
  proxy:
    requests:
      memory: "25Mi"
      cpu: "5m"
    limits:
      memory: "64Mi"
      cpu: "100m"

autoscaling: false
scaleAt:
  # These are expressed as a percentage of resources.requests, not resources.limits
  memoryPercentage: 150
  cpuPercentage: 200
replicas: 1
maxReplicas: 1
rollingUpdate:
  maxSurge: 1
  maxUnavailable: 1

dns:
  enabled: false
  wellKnownPort: 8080

gcp:
  project: ras-rm-dev
  seftUpload:
    project: ras-rm-sandbox
    bucket:
      name: bucket
      prefix: ""
    topic: topic
  collectionInstrument:
    bucket:
      name: "ras-rm-seft-ci-dev"
      prefix: ""

seftGCS:
  enabled: false

gnu:
  recipient: dev@example.com
  fingerprint: ED1B7A3EADF95687
