language: python

env:
- CODECOV_TOKEN="d58091c4-cca2-4533-b419-bac51ed1511f"

python:
  - "2.7"

install:
  - "pip install -r requirements.txt"
  - "pip install -r requirements_for_test.txt"

script:
  - ./scripts/run_tests.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)

dist: trusty

addons:
   postgresql: "9.6"