swagger: '2.0'
basePath: /api
info:
  description: Initial API for the Collection Instrument microservice.
  version: 1.0.0
  title: Collection Instrument API
  contact:
    email: martin.thomas@ons.gov.uk


securityDefinitions:
  accessCode:
    type: oauth2
    # This should be updated to the Token URL of your OAuth provider.
    tokenUrl: http://uaa.ons.gov.uk/oauth/token
    # This should be updated to the Authorization URL of your OAuth provider.
    authorizationUrl: http://uaa.ons.gov.uk/oauth/auth
    flow: accessCode
    scopes:
      write: allows modifying resources
      read: allows reading resources

security:
  - accessCode:
    - read

tags:
- name: backstage
  description: Operations available to internal clients
- name: frontstage
  description: Operations available to external clients
schemes:
- https
paths:
  /collection-instruments/id/{id}:
    options:
      tags:
      - frontstage
      - backstage
      summary: View the available representations for a given collection instrument
      produces:
      - application/vnd.collection+json
      parameters:
      - name: id
        in: path
        description: ID of collection instrument to return
        required: true
        type: string
      responses:
        200:
          description: Collection of available representations for a collection instrument
          schema:
            $ref: '#/definitions/vnd.collection+json'
        404:
          description: Collection instrument not found
    get:
      tags:
      - frontstage
      - backstage
      summary: Get a collection instrument by ID
      description: Returns a single collection instrument
      operationId: getCollectionInstrumentById
      produces:
      - application/vnd.ons.collectioninstrument+json
      - application/vnd.ms-excel
      parameters:
      - name: id
        in: path
        description: ID of collection instrument to return
        required: true
        type: string
      responses:
        200:
          description: Collection instrument representation
          headers:
            ETag:
              type: string
              description: The current ETag for the collection instrument, e.g. "5635635636356356"
          schema:
            $ref: '#/definitions/collectioninstrument'

        400:
          description: Invalid ID supplied
        404:
          description: Collection instrument not found
    put:
      tags:
      - backstage
      summary: Adds a binary representation to an existing collection instrument
      description: Adds a collection instrument binary representation to the system
      security:
        - accessCode:
          - write
      consumes:
      - multipart/form-data
      parameters:
      - name: id
        in: path
        description: 'ID of collection instrument to update'
        required: true
        type: string
      - name: binaryCollectionInstrument
        in: formData
        description: 'Binary collection instrument to add'
        required: true
        type: file
      - name: ETag
        in: header
        type: string
        description: The current ETag value for the collection instrument
      responses:
        201:
          description: item updated
          headers:
            ETag:
              type: string
              description: On successful update, the new ETag for the collection instrument will be included as a header, e.g. "5635635636356356"
        400:
          description: Invalid ID supplied
        409:
          description: Invalid ETag supplied

  /collection-instruments:
    get:
      tags:
      - frontstage
      - backstage
      summary: searches collection instruments
      description: |
        By passing in the appropriate options, you can search for available collection instruments
      produces:
      - application/vnd.collection+json
      parameters:
      - in: query
        name: searchString
        description: pass an optional search string for looking up collection instruments based on classifier
        required: false
        type: string
      - in: query
        name: skip
        description: number of records to skip for pagination
        type: integer
        format: int32
        minimum: 0
      - in: query
        name: limit
        description: maximum number of records to return
        type: integer
        format: int32
        minimum: 0
        maximum: 50
      responses:
        200:
          description: search results matching criteria
        400:
          description: bad input parameter
    post:
      tags:
      - backstage
      summary: adds a collection instrument
      description: Adds a collection instrument to the system
      security:
        - accessCode:
          - write
      consumes:
      - application/vnd.ons.collectioninstrument+json
      parameters:
      - in: body
        name: collectionInstrument
        description: Collection instrument to add
        schema:
          $ref: '#/definitions/collectioninstrument'
      responses:
        201:
          description: item created
          headers:
            Location:
              type: string
              description: Location of the newly created resource
            ETag:
              type: string
              description: On successful creation, the new ETag for the collection instrument will be included as a header, e.g. "5635635636356356"
        400:
          description: invalid input, object invalid
        409:
          description: an existing item already exists

  /collection-instrument-bundles:
    post:
      tags:
      - backstage
      summary: adds a collection instrument bundle
      description: Adds a collection instrument bundle to the system.
      security:
        - accessCode:
          - write
      consumes:
      - application/vnd.ons.collectioninstrumentbundle+json
      parameters:
      - in: body
        name: collectionInstrumentBundle
        description: Collection instrument bundle to process
        schema:
          $ref: '#/definitions/collectioninstrument'
      responses:
        202:
          description: bundle accepted for processing
          headers:
            Location:
              type: string
              description: Location of the newly created resource
            ETag:
              type: string
              description: On successful creation, the new ETag for the collection instrument bundle will be included as a header, e.g. "5635635636356356"
        400:
          description: invalid input, object invalid

definitions:
  vnd.collection+json:
    type: object
    properties:
      version:
        type: string
        example: "1.0"
      href:
        type: string
        example: "/collectioninstrument/id/12345678"
      links:
        type: array
        items:
          type: object
          properties:
            rel:
              type: string
              example: "self"
            href:
              type: string
              example: "/collectioninstrument/id/12345678"
            type:
              type: string
              example: "application/vnd.ons.collectioninstrument+json"
  classifiers:
    type: object
    required:
    - classifierType
    - classifier
    properties:
      classifierType:
        type: array
        items:
          type: string
        enum:
          - "RU_REF"
          - "COLLECTION_EXERCISE"
          - "SIC"
          - "LEGAL_BASIS"
        example: "RU_REF"
      classifier:
        type: string
        example: "1731"
  collectioninstrument:
    type: object
    required:
    - id
    - surveyId
    - ciType
    properties:
      id:
        type: string
        format: urn
        example: urn:ons.gov.uk:id:ci:001.234.56789
      surveyId:
        type: string
        format: urn
        example: urn:ons.gov.uk:id:survey:001.234.56789
      ciType:
        type: array
        items:
          type: string
        enum:
          - "ONLINE"
          - "OFFLINE"
        example: "OFFLINE"
      classifiers:
        $ref: '#/definitions/classifiers'
