# coding: utf-8

from __future__ import absolute_import
from swagger_server.models.vnd_collectionjson_links import VndCollectionjsonLinks
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class VndCollectionjson(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, href: str=None, version: str=None, links: List[VndCollectionjsonLinks]=None):
        """
        VndCollectionjson - a model defined in Swagger

        :param href: The href of this VndCollectionjson.
        :type href: str
        :param version: The version of this VndCollectionjson.
        :type version: str
        :param links: The links of this VndCollectionjson.
        :type links: List[VndCollectionjsonLinks]
        """
        self.swagger_types = {
            'href': str,
            'version': str,
            'links': List[VndCollectionjsonLinks]
        }

        self.attribute_map = {
            'href': 'href',
            'version': 'version',
            'links': 'links'
        }

        self._href = href
        self._version = version
        self._links = links

    @classmethod
    def from_dict(cls, dikt) -> 'VndCollectionjson':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The vnd.collection+json of this VndCollectionjson.
        :rtype: VndCollectionjson
        """
        return deserialize_model(dikt, cls)

    @property
    def href(self) -> str:
        """
        Gets the href of this VndCollectionjson.

        :return: The href of this VndCollectionjson.
        :rtype: str
        """
        return self._href

    @href.setter
    def href(self, href: str):
        """
        Sets the href of this VndCollectionjson.

        :param href: The href of this VndCollectionjson.
        :type href: str
        """

        self._href = href

    @property
    def version(self) -> str:
        """
        Gets the version of this VndCollectionjson.

        :return: The version of this VndCollectionjson.
        :rtype: str
        """
        return self._version

    @version.setter
    def version(self, version: str):
        """
        Sets the version of this VndCollectionjson.

        :param version: The version of this VndCollectionjson.
        :type version: str
        """

        self._version = version

    @property
    def links(self) -> List[VndCollectionjsonLinks]:
        """
        Gets the links of this VndCollectionjson.

        :return: The links of this VndCollectionjson.
        :rtype: List[VndCollectionjsonLinks]
        """
        return self._links

    @links.setter
    def links(self, links: List[VndCollectionjsonLinks]):
        """
        Sets the links of this VndCollectionjson.

        :param links: The links of this VndCollectionjson.
        :type links: List[VndCollectionjsonLinks]
        """

        self._links = links

