service:
    NAME: ras-collection-instrument
    VERSION: 1.0.2
    SCHEME: http
    HOST: 0.0.0.0
    PORT: 8082
    DEBUG: False
    LOG_LEVEL: info
    ONS_CRYPTOKEY: crypto_key
    SECURITY_USER_NAME: test_user_name
    SECURITY_USER_PASSWORD : test_user_password
    RABBITMQ_AMQP: rabbitmq_amqp
    UPLOAD_FILE_EXTENSIONS: xls,xlsx
    MAX_UPLOAD_FILE_NAME_LENGTH: 50

dependencies:
    ras-ci-db:
        schema: ras_ci
        uri: "sqlite:///ras-ci"
    case-service:
        scheme: http
        host: localhost
        port: 8171
    collectionexercise-service:
        scheme: http
        host: localhost
        port: 8145
    survey-service:
        scheme: http
        host: localhost
        port: 8080